Repository Mayuresh-22/Minglr, pull requests merged in 2023-10, with the labels that each got.

#7 Updating Patch 2 branch
  account.php
  back/connection.php
  back/env.php
  back/logout.php
  db/connection.php
  db/validate.php
  feed.php
  message.php
  post.php
  style/account.css
Labels: hacktoberfest, hacktoberfest-accepted

#8 Mayuresh 22 patch 2 redirect parameter added
  feed.php
Labels: hacktoberfest, hacktoberfest-accepted

#9 Added hover effects when we navigate to the tabs at the top for better UX
  style/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#12 Update Index.php to redirect user on feed page after login.
  index.php
Labels: hacktoberfest, hacktoberfest-accepted, bug fixed

#16 Added Demo file
  uploads/844882_1305.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#17 Added Do Not Remove Flag to the img and added basic auth details
  db/connection.php
  uploads/844882_1305.jpg
  uploads/DO_NOT_REMOVE_THIS_IMG.png
Labels: hacktoberfest, hacktoberfest-accepted

#15 Enhanced navigation bar styling for a more elegant look.
  about-us.php
  account.php
  feed.php
  index.php
  message.php
  style/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#18 Create LEARN.md
  LEARN.md
Labels: hacktoberfest, hacktoberfest-accepted

#19 Create LICENSE
  LICENSE
Labels: hacktoberfest, hacktoberfest-accepted
