Repository Mayuresh-22/Minglr, pull requests merged in 2024-01, with the labels that each got.

#39 added favicon
  about-us.php
  account.php
  feed.php
  index.php
  message.php
Labels: SWOC S4, SWOC S4 Accepted

#41 Send-message button made responsive
  account.php
  style/account.css
Labels: SWOC S4, SWOC S4 Accepted

#45 Made title bar responsive
  account.php
  style/style.css
Labels: SWOC S4, SWOC S4 Accepted

#50 Fixing Logout Functionality
  back/logout.php
Labels: SWOC S4, SWOC S4 Accepted

#53 added hover effects
  style/style.css
Labels: SWOC S4, SWOC S4 Accepted

#57 formated phpcode
  back/logout.php
  db/validate.php
  post.php
  pvtmsg.php
Labels: SWOC S4, SWOC S4 Accepted

#63 Feat: Enhanced the UI of the footer by changing it's color
  style/style.css
Labels: SWOC S4, SWOC S4 Accepted

#59 Added Max and Min Width of Text Area
  account.php
  style/account.css
  style/feed.css
Labels: SWOC S4, SWOC S4 Accepted

#64 Fixing RegEx-62
  db/validate.php
Labels: SWOC S4, HARD, SWOC S4 Accepted

#70 Made message page responsive
  message.php
Labels: SWOC S4, EASY, SWOC S4 Accepted

#76 Fixed photos section BUG
  account.php
  feed.php
  style/feed.css
Labels: SWOC S4, HARD, SWOC S4 Accepted

#71 Fixing potential changes to footer for improved user experience 67
  about-us.php
  account.php
  feed.php
  index.php
  message.php
  style/style.css
Labels: SWOC S4, EASY, SWOC S4 Accepted

#80 [feat] Added password validation on Registration form. Solved #77
  db/validate.php
  index.php
  style/style.css
Labels: SWOC S4, MEDIUM, SWOC S4 Accepted

#95 Footer Styling Done
  about-us.php
  account.php
  feed.php
  index.php
  message.php
  style/style.css
Labels: SWOC S4, EASY, SWOC S4 Accepted

#101 Changes done for issue: #100
  back/search.php
  index.php
Labels: SWOC S4, EASY, SWOC S4 Accepted
